### ISSUE TITLE
Data set type

### ISSUE THREAD

**Issue by yjiakang** [PengfanZhang/Rbec#2]
Thanks for your amazing tool for analysis related to Syncom. I am wondering weather it is compatible for bacteria 16S full length data or ITS sequences?
Thanks in advance.

**Comment by PengfanZhang** [comment]
Hi,

Thanks for your interest in our package. Unfortunately, we haven't tested the efficiency of Rbec in analyzing the full-length amplicon sequencing. Some parameters definitely should be modified when analyzing those long reads. I'm glad to evaluate Rbec with full-length amplicon sequencing if you could share some dataset with me.

Best,
Pengfan
